apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Release.Name}}
  labels:
    app: {{ .Release.Name}}
    service: {{ .Release.Name}}
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: {{ .Release.Name}}
