apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-{{ .Release.Name}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployment-{{ .Release.Name}}
  minReplicas: {{ .Values.docker.minReplicas}}
  maxReplicas: {{ .Values.docker.maxReplicas}}
  # targetCPUUtilizationPercentage: 50
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50